/* Generate a published key file from a quizdata module.

     node genkey.js germany > germany.key.js
     node genkey.js france  > france.key.js

   Each quizdata/<name>.js holds the term list as real latitude/longitude plus
   the map's geographic bounds. Positions are converted with the same linear
   (equirectangular) mapping Wikipedia uses to place pins on that map image:

     x = (lon - left) / (right - left)      y = (top - lat) / (top - bottom)

   The output is only correct for the map file named in the data module. A
   differently cropped or projected map needs its own bounds.                 */

const name = process.argv[2];
if (!name) { console.error('usage: node genkey.js <quiz>   e.g. node genkey.js france'); process.exit(2); }
const Q = require('./quizdata/' + name + '.js');

const { top, bottom, left, right } = Q.bounds;
const X = lon => (lon - left) / (right - left);
const Y = lat => (top - lat) / (top - bottom);

// ---- convert ----
const terms = Q.terms.map(([label, kind, pts, tolOverride]) => ({
  label, kind, tolOverride,
  pts: pts.map(([lat, lon]) => [+X(lon).toFixed(4), +Y(lat).toFixed(4)]),
}));

// ---- validate ----
const bad = [];
terms.forEach(t => t.pts.forEach(([x, y]) => {
  if (x < 0 || x > 1 || y < 0 || y > 1) bad.push(`${t.label}: ${x},${y}`);
}));
if (bad.length) { console.error('OUT OF BOUNDS (off the map image):\n' + bad.join('\n')); process.exit(1); }

const dupes = terms.map(t => t.label).filter((l, i, a) => a.indexOf(l) !== i);
if (dupes.length) { console.error('DUPLICATE LABELS: ' + dupes.join(', ')); process.exit(1); }

// ---- auto tolerance for cities ----
// A city must not be satisfied by a click aimed at a different city. Cities sitting
// inside a region (Cologne in the Rhineland) is expected, so regions are ignored here.
const d = (a, b) => Math.hypot(a[0]-b[0], (a[1]-b[1]) * Q.aspect);
const cities = terms.filter(t => t.kind === 'city');
cities.forEach(c => {
  let nearest = Infinity;
  cities.forEach(o => { if (o !== c) nearest = Math.min(nearest, d(c.pts[0], o.pts[0])); });
  const half = nearest * 100 / 2;                       // half the gap, as % of width
  c.tol = +Math.max(Q.minCityTol, Math.min(Q.tol, half)).toFixed(1);
});

// confirm no city can be claimed by a click aimed at another city
const clashes = [];
cities.forEach(a => cities.forEach(b => {
  if (a !== b && d(a.pts[0], b.pts[0]) * 100 <= b.tol) clashes.push(`${a.label} click satisfies ${b.label}`);
}));
if (clashes.length) { console.error('CITY CLASH:\n' + clashes.join('\n')); process.exit(1); }

// ---- emit ----
const rows = terms.map(t => {
  const tol = t.tolOverride !== undefined ? t.tolOverride : t.tol;
  return '  {"label":' + JSON.stringify(t.label) +
         ',"line":' + (t.kind === 'line') +
         (tol !== undefined ? ',"tol":' + tol : '') +
         ',"pts":' + JSON.stringify(t.pts) + '}';
});

console.log(`/* ${Q.title}
   Generated by:  node genkey.js ${Q.id}
   From geographic coordinates in quizdata/${Q.id}.js, mapped onto ${Q.map}
   (bounds ${top}N ${bottom}N ${left}E ${right}E, equirectangular). Only correct for that image.

   line:true = river; anywhere along the path counts.
   tol:      = this term's own accepted radius, overriding the global one.
               Cities get a tighter radius so neighbours stay distinguishable. */
window.MAPQUIZ_KEYS = window.MAPQUIZ_KEYS || {};
window.MAPQUIZ_KEYS[${JSON.stringify(Q.id)}] = {
 "title": ${JSON.stringify(Q.title)},
 "version": ${Q.version},
 "map": ${JSON.stringify(Q.map)},
 "tol": ${Q.tol},
 "terms": [
${rows.join(',\n')}
 ]
};`);

// ---- report to stderr so it doesn't pollute the key file ----
console.error(`${Q.title}: ${terms.length} terms, ${cities.length} cities, ` +
              `${terms.filter(t => t.kind === 'line').length} rivers, version ${Q.version}`);
console.error('city tolerances (% of map width):');
cities.forEach(c => console.error(`  ${c.label.padEnd(20)} ${String(c.tol).padStart(5)}%`));
