/* Answer key generated by genkey.js from geographic coordinates, mapped onto
   the Wikipedia "Relief Map of Germany" location-map bounds:
     top 55.1N  bottom 47.2N  left 5.5E  right 15.5E, equirectangular.
   x = (lon - 5.5) / 10        y = (55.1 - lat) / 7.9
   Only correct for THAT map image. A different map needs a new key.

   Terms and numbering follow Geoquiz--Germany.docx exactly.

   line:true = river; anywhere along the path counts.
   tol:      = this term's own accepted radius, overriding the global one.
               Cities get a tighter radius so neighbours stay distinguishable. */
window.MAPQUIZ_KEY = {
 "version": 7,
 "map": "Relief_Map_of_Germany.png",
 "tol": 8,
 "terms": [
  {"label":"Black Forest","line":false,"pts":[[0.265,0.8165],[0.27,0.8481],[0.265,0.8861],[0.255,0.9177],[0.26,0.8671]]},
  {"label":"Rhine River","line":true,"pts":[[0.336,0.9418],[0.209,0.9557],[0.206,0.8987],[0.229,0.8253],[0.281,0.7709],[0.294,0.7114],[0.277,0.6468],[0.21,0.6],[0.16,0.5519],[0.146,0.5266],[0.122,0.4899],[0.123,0.462],[0.092,0.4354],[0.075,0.4139]]},
  {"label":"Oder River","line":true,"pts":[[0.92,0.3848],[0.905,0.3481],[0.914,0.3165],[0.885,0.2848],[0.878,0.2582],[0.885,0.2342],[0.882,0.2127]]},
  {"label":"Elbe River","line":true,"pts":[[0.865,0.5291],[0.824,0.5127],[0.78,0.4747],[0.75,0.4481],[0.715,0.4089],[0.613,0.3759],[0.635,0.3228],[0.625,0.2671],[0.575,0.2481],[0.506,0.219],[0.449,0.1962],[0.375,0.1608],[0.335,0.1532]]},
  {"label":"Danube River","line":true,"pts":[[0.3,0.9051],[0.332,0.9],[0.372,0.8873],[0.412,0.8595],[0.449,0.8481],[0.51,0.8291],[0.569,0.8063],[0.637,0.7823],[0.66,0.7696],[0.708,0.7873],[0.746,0.7924],[0.796,0.8266]]},
  {"label":"North Sea","line":false,"pts":[[0.21,0.1139],[0.15,0.0759],[0.11,0.1519],[0.25,0.1329],[0.08,0.0633]]},
  {"label":"Bavaria","line":false,"pts":[[0.56,0.6772],[0.61,0.7342],[0.64,0.7848],[0.59,0.8354],[0.71,0.7848],[0.54,0.7215],[0.54,0.8544]]},
  {"label":"Saxony","line":false,"pts":[[0.71,0.4747],[0.79,0.5063],[0.85,0.5253],[0.76,0.4684],[0.74,0.4937]]},
  {"label":"Prussia","line":false,"pts":[[0.71,0.2911],[0.79,0.2405],[0.67,0.3544],[0.85,0.2658],[0.83,0.3165],[0.75,0.2152]]},
  {"label":"Alsace-Lorraine","line":false,"pts":[[0.225,0.8253],[0.184,0.9304],[0.068,0.757],[0.195,0.8608],[0.14,0.7848],[0.17,0.7722]]},
  {"label":"Pomerania","line":false,"pts":[[0.788,0.1278],[0.759,0.1],[0.87,0.1519],[0.95,0.1139],[0.91,0.1899]]},
  {"label":"Denmark","line":false,"pts":[[0.38,0.019],[0.43,0.0127],[0.34,0.0063],[0.49,0.019]]},
  {"label":"Belgium","line":false,"pts":[[0.007,0.5646],[0.03,0.5316],[0.05,0.5949],[0.04,0.6203]]},
  {"label":"France","line":false,"pts":[[0.01,0.8101],[0.04,0.8734],[0.07,0.9367],[0.08,0.9684],[0.02,0.7595]]},
  {"label":"Luxembourg","line":false,"pts":[[0.063,0.6684],[0.063,0.6962],[0.055,0.6392],[0.035,0.6772]]},
  {"label":"Liechtenstein","line":false,"tol":4,"pts":[[0.403,0.9937],[0.401,0.9975]]},
  {"label":"Austria","line":false,"pts":[[0.879,0.8608],[0.755,0.9241],[0.81,0.8861],[0.69,0.9494],[0.95,0.8671],[0.59,0.9684]]},
  {"label":"Poland","line":false,"pts":[[0.94,0.3418],[0.905,0.2114],[0.95,0.5063],[0.97,0.3924],[0.98,0.5316]]},
  {"label":"Czech Republic","line":false,"pts":[[0.894,0.6354],[0.788,0.6772],[0.95,0.6013],[0.88,0.7342],[0.75,0.6962]]},
  {"label":"Switzerland","line":false,"pts":[[0.304,0.9772],[0.209,0.9557],[0.388,0.962],[0.24,0.9873],[0.34,0.9684]]},
  {"label":"Hamburg","line":false,"tol":5.8,"pts":[[0.4494,0.1961]]},
  {"label":"Berlin","line":false,"tol":2.5,"pts":[[0.7905,0.3266]]},
  {"label":"Wittenberg","line":false,"tol":4.5,"pts":[[0.715,0.4092]]},
  {"label":"Potsdam","line":false,"tol":2.5,"pts":[[0.7559,0.3423]]},
  {"label":"Kiel","line":false,"tol":5.8,"pts":[[0.4635,0.0984]]},
  {"label":"Cologne","line":false,"tol":8,"pts":[[0.146,0.5268]]},
  {"label":"Frankfurt-am-Mein","line":false,"tol":8,"pts":[[0.3182,0.6316]]},
  {"label":"Munich","line":false,"tol":8,"pts":[[0.6076,0.8814]]},
  {"label":"Hannover","line":false,"tol":8,"pts":[[0.4236,0.3448]]},
  {"label":"The Rhineland","line":false,"pts":[[0.14,0.4937],[0.16,0.5443],[0.2,0.6076],[0.18,0.6582],[0.17,0.5759]]},
  {"label":"Lake Constance","line":false,"pts":[[0.385,0.9494],[0.41,0.9557],[0.37,0.9392]]},
  {"label":"The Alps","line":false,"pts":[[0.27,0.9873],[0.41,0.9747],[0.53,0.981],[0.64,0.962],[0.75,0.9557],[0.69,0.9684],[0.81,0.9494]]},
  {"label":"Vosges Mountains","line":false,"pts":[[0.152,0.8608],[0.145,0.8924],[0.16,0.8418],[0.15,0.9114]]},
  {"label":"Rhineland","line":false,"pts":[[0.14,0.4937],[0.16,0.5443],[0.2,0.6076],[0.18,0.6582],[0.17,0.5759]]},
  {"label":"The Ruhr","line":false,"pts":[[0.145,0.4557],[0.17,0.4582],[0.195,0.4557],[0.15,0.462],[0.18,0.4494]]}
 ]
};
